# External gems
gems:
  - jekyll-archives # Not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

# Site settings
name: Oak Technical Services
version: 0.13.2
google_analytics_ua:

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/thoughts/:num/"
inter_post_navigation: true
permalinks: pretty
permalink: "/thoughts/:title/"
include: ["pages", "thoughts"]
future: true
safe: false
# This needs updated to work in production
baseurl: "http://greyfox33.github.io"
repos:

sass:
  sass_dir: assets/css


collections:
  visual:
    output: true
    permalink: /:path/
  layout-system:
    output: true
    permalink: /:path/
  elements:
    output: true
    permalink: /:path/
  components:
    output: true
    permalink: /:path/

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    style: none
    category: '/category/:name/'
    tag: '/tag/:name/'

# Build settings
markdown: kramdown
exclude:
- ".ruby-version"
- ".sass-cache"
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- config
- css
- img
- js
- manifest.yml
- node_modules
- package.json
- vendor
- gulpfile.js
- circle.yml
- assets/src
